var os = require("os")
console.log(os.arch())
console.log(os.hostname())
console.log(os.type())
console.log(os.release())
console.log(os.uptime()/60)
console.log(os.platform())
freemem=(os.freemem())/(1024*1024*1024)
console.log(Math.floor(freemem)+"gb")
totalmem = (os.totalmem())/(1024*1024*1024)
console.log(Math.floor(totalmem)+"gb")
console.log(os.userInfo())
console.log(os.networkInterfaces())
console.log(os.loadavg())
console.log(os.endianness())